### ISSUE TITLE
Model link missing

### ISSUE THREAD

**Issue by AdrianaJeanne** [YSerin/TMI_SwitchableCycleGAN#1]
Hi, 
The link to the trained model is not working anymore. Is it possible to provide the model?

Thank you in advance for your help

**Comment by Haog1999** [comment]
Hi, 
Both the links to the dataset and the trained model are out-of-date. Is there anybody could help?

Thank you so much!

**Comment by YSerin** [comment]
We have updated the links to the model weights and the sample data.

Thanks!
